#!/bin/bash


echo "SkyGate - Other Software Installation"
echo "====================================="

pushd ~

echo -e "\n\nInstalling SSDV"
echo        "==============="

git clone https://github.com/fsphil/ssdv.git
cd ssdv
sudo make install

echo -e "\n\nInstalling RTL SDR"
echo        "=================="

cd ~  
git clone https://github.com/daveake/rtl-sdr.git  
cd rtl-sdr  
mkdir build  
cd build  
cmake ../ -DINSTALL_UDEV_RULES=ON -DDETACH_KERNEL_DRIVER=ON  
make  
sudo make install  
sudo ldconfig  

echo -e "\n\nInstalling dl-fldigi"
echo        "===================="

cd ~
git clone git://github.com/ukhas/dl-fldigi.git  
cd dl-fldigi  
git checkout DL3.1  
git submodule init  
git submodule update
sudo sed -e "s/TESTS/#TESTS/g" -i src/Makefile.am

popd
